### ISSUE TITLE
Support smtpapi

### ISSUE THREAD

**Issue by bedeoverend** [feathersjs/feathers-sendgrid#2]
Is supporting `smtpapi` something on the roadmap? Either by just passing it through from `data` and adding it into `params` during `_formatData` or via a more abstracted interface?

**Comment by corymsmith** [comment]
@bedeoverend I hadn't planned on it yet as I only needed basic email sending at first but this would be a good addition. 

It looks like you may be able to use feathers-mailer that @ahdinosaur just wrote: https://github.com/feathersjs/feathers-mailer

Here's an example of using node-mailer and smtpapi:
https://github.com/sendgrid/smtpapi-nodejs

**Comment by bedeoverend** [comment]
@corymsmith `feathers-mailer` looks great, thanks. I meant smtpapi specifically for sendgrid - my use case was for using templates / substitutions in templates etc. rather than smtpapi more generally, I just suggested smtpapi as it would be the quickest access to those features.

But `feathers-mailer` with a sendgrid transport would fit my use case well for now, thanks!

**Comment by ekryski** [comment]
:+1: We'll leave this issue open. Probably won't get to this for 3-4 weeks though.

**Comment by ekryski** [comment]
This should now support this as you can provide whatever the V3 API supports.
